name: 'Publish Coffee Deals'
on:
  schedule:
    - cron:  '0 5 * * *'
  workflow_dispatch:
  push: 
    branches:
    - main
jobs:
  gather-csv:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
    - name: Clone Repo
      uses: actions/checkout@v4
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install Dependencies
      run: |
              pip install poetry
              poetry install
      shell: bash
    - name: Create CSV
      run: |
              printf "" > docs/coffeedeals.csv
              poetry run python src/coffeedeals/scrape_shopify.py >> docs/coffeedeals.csv
    - name: Commit new CSV to github
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        file_pattern: 'coffeedeals.csv'

  github-pages-deploy:
    # Add a dependency to the build job
    needs: gather-csv

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action
